### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aglalit** [Josee9988/Compress-PDFs#3]
# **🐞 Bug Report**

Doesn't work, here is the log:

Uploading file...
Traceback (most recent call last):
  File "compress.py", line 51, in <module>
    task.execute()
  File "/usr/local/lib/python3.8/site-packages/pylovepdf/task.py", line 169, in execute
    self.upload()
  File "/usr/local/lib/python3.8/site-packages/pylovepdf/task.py", line 79, in upload
    file.server_filename = response.server_filename
AttributeError: 'Response' object has no attribute 'server_filename'

**Comment by Josee9988** [comment]
Have you renamed the .env.example to .env and modified it with your credentials?

**Comment by aglalit** [comment]
> Have you renamed the .env.example to .env and modified it with your credentials?

Yes. I'll check my machine for firewall issues. Also, maybe there is a problem with a large file (50MB), which took too long to upload, so it broke the pipeline.

**Comment by Josee9988** [comment]
Also check to choose the a directory with at least 2 files because there is an unfixed bug that may occur if you only upload 1 file.
(This script is still untested and in beta versions so errors and unexpected bugs might happen)

**Comment by Josee9988** [comment]
Did it work @aglalit ?
